# Generated by Django 4.2.7 on 2023-12-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='学号'),
        ),
    ]
